import { Poppins } from "next/font/google";
import "./globals.css";
import NextAuthSession from "@/provider/NextAuthSession";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";
import ThemeProvider from "@/provider/ThemeProvider";


const poppins = Poppins({
  weight: ['100', '200', '300', '400', '400', '500', '600']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthSession>
      <html lang="en" data-theme="carelight">

        <body
          className={`${poppins.className} antialiased`}
        >
          <ThemeProvider></ThemeProvider>
          <header className="w-11/12 mx-auto p-2">
            <Navbar></Navbar>
          </header>
          <main className="w-11/12 mx-auto p-2">
            {children}
          </main>
          <footer >
            <Footer></Footer>
          </footer>
        </body>
      </html>
    </NextAuthSession>
  );
}
